### PR TITLE
Silence warnings in examples

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
I hate panics and I hate warnings so I didn't want to introduce the former just to cure the latter. ;)

**Comment by jamwaffles** [comment]
Ha, I hate both too, but I think in the examples' case I'd rather it panicked. I think it's easier to pick up what went wrong with a debugger than just silently(?) continuing with an unused var, and the program can't really do much else at that point. Would you mind changing them to `.unwrap()`s?

**Comment by therealprof** [comment]
I hate debuggers, too. 😉 But I'll `unwrap()` it for you.

**Comment by therealprof** [comment]
Done.

**Comment by jamwaffles** [comment]
There's no pleasing some people 😂 but thanks for the changes 😃. The other examples should get updated but let's do that as we come to them.

**Comment by therealprof** [comment]
The other examples were fine already.

**Pull request merged**
