### PR TITLE
Use much less memory in I2C interface

### LINKED ISSUE #6: Fix duplicate buffer in I2C code
[`send_data()`](https://github.com/jamwaffles/ssd1306/blob/master/src/interface/i2c.rs#L28-L40) should be using less memory. @scowcron's [implementation](https://github.com/EdgewaterDevelopment/rust-ssd1306/blob/master/src/prelude.rs#L27) uses buffered chunks which might be a good way to go. Adding the initial `0x40` to the beginning of the buffer makes using another buffer a necessity at the moment.

### PR DESCRIPTION
**Pull request by jamwaffles**
Gone from 1025 byte buffer down to 17, although sending data to the display is marginally less efficient. Should be fine.

@scowcron This is from your `rust-ssd1306` crate. Any thoughts?

Fixes #6.

### CODE REVIEW

**Comment by scowcron** [comment]
other than the CI not working, looks good.

I was getting ready to submit a near identical PR. The old way would have failed on [stm32f30x](https://github.com/japaric/stm32f30x-hal/blob/d51a39b0ad1665c04ecead9ab148a5520dca139b/src/i2c.rs#L185) anyway.

I don't think there's anything to worry about sending an extra 64 bytes for every 1k at this scale. I'd rather eliminate the buffer entirely but the changes haven't come down yet that make that possible.

Ship it.

**Comment by jamwaffles** [comment]
I'll remove CircleCI until we decide what to do with CI in general. Forgot I added it tbh.

Good catch on the stm32f30x. I'm using the stm32f103 so there's probably a bunch of stuff I'm missing.

I'm not too bothered about the memory usage. Maybe on an AVR or PIC but not on these ARM chips.

**Comment by scowcron** [comment]
That `stm32f30x` is important because that's what japaric uses in all of his examples, which since he's the guy leading the charge means that's what a lot of people who try to pick this stuff up for the first time are going to be using. I have the f3 board he uses all the time, so I can be testing against that.

**Comment by jamwaffles** [comment]
Yeah I've seen some of his neato accelerometer stuff he's done with that chip. It's good to have a range of test hardware!

**Pull request merged**
