### PR TITLE
Different GraphicsMode optimization options

### PR DESCRIPTION
**Pull request by bugadani**
Hi! Thank you for helping out with SSD1306 development! Please:

- [ ] Check that you've added documentation to any new methods
- [ ] Rebase from `master` if you're not already up to date
- [ ] Add or modify an example if there are changes to the public API
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [ ] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [ ] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

In my use case, I'm using the display on an 8MHz SPI connection, which means a flush is around 1ms. This allows me to switch the partial update to a full update, and basically eliminate tracking of the dirty area.

I still need to benchmark this to see if there is any point in adding the extra complexity, but I wanted to open this draft to hear some of your thoughts on the matter.

By default, the implementation uses the old dirty area tracking method with the partial screen update, so it's hopefully backwards compatible.

### CODE REVIEW

**Comment by bugadani** [comment]
Oh, also this is based on #123, hence the duplicate commits.

**Comment by bugadani** [comment]
Just in case, please don't waste time on reviewing the code yet (since this was thrown together extremely quickly and has a ton of potential issues, including the crash of #123), only the general idea :)

**Comment by bugadani** [comment]
A speed bump of around 8% (117813 cycles instead of 128348 while drawing a piece of text) when using FastSetPixel. Tested on a nRF52832 @ 64MHz

**Comment by bugadani** [comment]
Since it's possible to draw to an otherwise unexpected location, I'm thinking about making it possible in FastSetPixel (or a different UncheckedFastSetPixel) to write to an unchecked address. It's already up to the user to draw to the right area, so I think an explicitly unsafe option is not that big deal to add.

**Comment by bugadani** [comment]
Closes #122

**Comment by bugadani** [comment]
I'm done modifying this. There is a single compare that could be optimized away iff it can be ensured that every write is inside the display area, but I don't think it would be worth the extra complexity and the risk.

**Comment by jamwaffles** [comment]
I like the idea of moving the dirty tracker to a separate struct for cleanliness, as well as the fix for #122, but I'm not sure I see a benefit to making it customisable with another associated type, particularly if we add this one on top of those added in #125. Is 1ms update really too slow for your application?

**Comment by bugadani** [comment]
My benchmark is my original C code that was able to display a realtime sampled signal at 100fps. While I don't expect the same performance, I'm not even close to that with this patch either :) After #125, most of the set_pixel code is the 4 min/max calls, so yeah, I would like to see those go away.

**Comment by therealprof** [comment]
100fps? I take it that's not over 400kHz I2C... It seems dubious at least that the min/max would significantly slow down the drawing.

**Comment by bugadani** [comment]
I'm using 8MHz SPI

**Comment by bugadani** [comment]
I don't know why I didn't think of this, but I could just use a tailor-made graphics mode implementation for my use case...

**Comment by bugadani** [comment]
I'm closing this, if someone wants their `GraphicsMode` to be faster, they can reimplement it easy enough and that basically makes the added complexity of this PR not worth breaking everybody's code.

**Pull request closed without merging**
