### PR TITLE
Move bounded drawing calculation from interfaces into the only call site

### PR DESCRIPTION
**Pull request by therealprof**
Hi! Thank you for helping out with SSD1306 development! 

Please:

- [x] Check that you've added documentation to any new methods
- [x] Rebase from `master` if you're not already up to date
- [ ] Add or modify an example if there are changes to the public API
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [x] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

Remove some code duplication in bounded box drawing by moving the bounding box calculation from the interface specific `send_bounded_data` into the only call site and reuse the regular `send_data` function.

### CODE REVIEW

**Comment by therealprof** [comment]
It's a bit weird that this is a world-public interface. But I've added the entry as requested.

**Comment by therealprof** [comment]
NB: I've also tested the I2C version of this in one of my projects.

**Comment by jamwaffles** [comment]
> It's a bit weird that this is a world-public interface. But I've added the entry as requested.

It should probably be private, no? I'm happy to make that breaking change. If someone really wants it, we can come up with a better solution down the road.

p.s. needs a rebase

**Comment by therealprof** [comment]
@jamwaffles Privatizing doesn't really work, already tried. It's too exposed but hey, maybe we're completely changing it anyways. 😅

**Pull request merged**
