### PR TITLE
Fix display rotation in terminal mode

### PR DESCRIPTION
**Pull request by alvinhochun**
Hi! Thank you for helping out with SSD1306 development! Please:

- ~~Check that you've added documentation to any new methods~~
- [x] Rebase from `master` if you're not already up to date
- ~~Add or modify an example if there are changes to the public API~~
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [x] Check that your branch is up to date with master and that CI is passing once the PR is opened

## Fix display rotation in terminal mode

Fix display rotation in terminal mode, referencing #145.

Only tested with a 96x16 display module.

### CODE REVIEW

**Comment by bugadani** [comment]
I can't confirm right now but I think the slight differences between this and #145 might not work for all displays. I'll try and check this week. Also pinging @jamwaffles just in case this PR was not noticed at all.

**Comment by bugadani** [comment]
Actually, this seems to work just fine. Tested on 72x40, 96x16 and 128x32.

**Review by jamwaffles — APPROVED** [review]
Thanks for the fix, and thanks for confirming it works @bugadani

**Comment by jamwaffles** [comment]
Released in 0.5.2. Thanks for your patience!

**Pull request merged**
