### PR TITLE
Transform Command into a fixed array and a length and call send only …

### PR DESCRIPTION
**Pull request by therealprof**
…once

The previous way of calling send_commands() directly caused a lot of
code duplication and calls for the SPI interface layer. To work around
this issue I'm now assembling the data into a fixed sized array (Rust
does not allow varying return types on match) and a length which then is
unconditionally and only once passed over to the interface for
transmission. It's the most idiomatic way I could come up with without
grabbing for the nightly or unsafe toolset.

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
Before:
```
cargo bloat --release --example blinky
warning: unused manifest key: profile.dev.incremental
   Compiling ssd1306 v0.1.0 (file:///Users/egger/OSS/ssd1306)
    Finished release [optimized + debuginfo] target(s) in 3.0 secs

File  .text   Size Name
0.0%   1.3%    80B [10 Others]
0.9%  51.9% 3.0KiB ssd1306::command::Command::send
0.3%  14.3%   850B blinky::init
0.1%   7.0%   414B cortex_m_rt::reset_handler
0.1%   4.7%   278B <ssd1306::mode::graphics::GraphicsMode<DI>>::flush
0.1%   3.8%   224B __aeabi_memcpy4
0.1%   2.9%   174B __aeabi_memset4
0.0%   2.6%   152B blinky::draw_square
0.0%   2.5%   148B __aeabi_memset
0.0%   2.3%   138B cortex_m_rtfm::atomic
0.0%   2.2%   134B <ssd1306::mode::graphics::GraphicsMode<DI>>::set_pixel
0.0%   1.6%    96B __aeabi_memcpy
0.0%   1.3%    78B blinky::idle
0.0%   0.5%    30B blinky::main
0.0%   0.2%    10B core::result::unwrap_failed
0.0%   0.2%    10B core::panicking::panic
0.0%   0.2%    10B core::panicking::panic_bounds_check
0.0%   0.2%    10B SVCALL
0.0%   0.2%    10B MEM_MANAGE
0.0%   0.2%    10B DEBUG_MONITOR
0.0%   0.2%    10B PENDSV
1.8% 100.0% 5.8KiB .text section size, the file size is 322.3KiB
```

After:

```
cargo bloat --release --example blinky
warning: unused manifest key: profile.dev.incremental
   Compiling ssd1306 v0.1.0 (file:///Users/egger/OSS/ssd1306)
    Finished release [optimized + debuginfo] target(s) in 1.72 secs

File  .text   Size Name
0.0%   2.3%    80B [10 Others]
0.3%  24.1%   850B blinky::init
0.2%  18.8%   662B ssd1306::command::Command::send
0.1%  11.7%   414B cortex_m_rt::reset_handler
0.1%   7.9%   278B <ssd1306::mode::graphics::GraphicsMode<DI>>::flush
0.1%   6.3%   224B __aeabi_memcpy4
0.1%   4.9%   174B __aeabi_memset4
0.1%   4.3%   152B blinky::draw_square
0.0%   4.2%   148B __aeabi_memset
0.0%   3.9%   138B cortex_m_rtfm::atomic
0.0%   3.8%   134B <ssd1306::mode::graphics::GraphicsMode<DI>>::set_pixel
0.0%   2.7%    96B __aeabi_memcpy
0.0%   2.2%    78B blinky::idle
0.0%   0.9%    30B blinky::main
0.0%   0.3%    10B core::result::unwrap_failed
0.0%   0.3%    10B core::panicking::panic
0.0%   0.3%    10B core::panicking::panic_bounds_check
0.0%   0.3%    10B SVCALL
0.0%   0.3%    10B MEM_MANAGE
0.0%   0.3%    10B DEBUG_MONITOR
0.0%   0.3%    10B PENDSV
1.2% 100.0% 3.4KiB .text section size, the file size is 291.3KiB
```

**Comment by jamwaffles** [comment]
Ha, I made an attempt at doing exactly the same thing a few nights ago but didn't get anywhere with it. Interestingly it doesn't reduce the I2C size at all, but the jump for SPI is quite significant :). I'll test it with an SPI display when I get home tonight.

**Comment by therealprof** [comment]
Yeah, tried a few other things but most of them failed due to match insisting on yielding identical (sized) types. Might have worked with some `Unsized` trickery or adding a trait to `Command` but I really didn't want to spend another tons of hours on this. It actually does reduce size in the I2C case a tiny bit as well but that's really negligible.

**Comment by jamwaffles** [comment]
Works on my SPI display :). Tested with `blinky` and `graphics`.

**Pull request merged**
