### PR TITLE
Clarify usage of display size

### LINKED ISSUE #140: Remove type parameter defaults related to display size.
The type parameter default on GraphicsMode et al. can cause confusion for newcomers. For the next major release, they (the paramter defaults, not the newcomers) should be removed.

### PR DESCRIPTION
**Pull request by bugadani**
Hi! Thank you for helping out with SSD1306 development! Please:

- [ ] Check that you've added documentation to any new methods
- [ ] Rebase from `master` if you're not already up to date
- [ ] Add or modify an example if there are changes to the public API
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [ ] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [ ] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

Place some comments that (hopefully) help with the confusion around using different display sizes.

Closes #140

### CODE REVIEW

**Comment by jamwaffles** [comment]
Would it be a better idea to remove the default `DSIZE = DisplaySize128x64` from `GraphicsMode`, `TerminalMode`, etc?

**Comment by jamwaffles** [comment]
Ah, I just saw #140. Let's go with that approach.

**Comment by bugadani** [comment]
Yes but only if you're fine with breaking changes :)

**Comment by jamwaffles** [comment]
Yep! That's fine. I need to get e-g 0.7 into this driver at some point too, so that's already breaking.

**Comment by bugadani** [comment]
@jamwaffles sorry for the noise, CI told me I'm a dummy.

**Review by jamwaffles — APPROVED** [review]
Sorry it took me so long to get to this. It all looks good to me!

**Pull request merged**
