### PR TITLE
Add Raspberry Pi example

### PR DESCRIPTION
**Pull request by btielen**
- [x] Check that you've added documentation to any new methods
- [x] Rebase from `master` if you're not already up to date
- [x] Add or modify an example if there are changes to the public API
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [x] Check that your branch is up to date with master and that CI is passing once the PR is opened
        _Current CI configuration is not passing, changed to configuration in the PR. That one succesful._

## PR description

Added a simple example based on a  existing example for the Raspberry Pi. Due to some strange dependencies problems, I had to switch to rust version 2021 (stabilized in rust 1.56) which automatically solved the problems.  Reconfigured and improved CircleCI configuration to support multiple examples for different targets. See #48 

Thanks to @PatrickLang for creating the first example.

### CODE REVIEW

**Comment by btielen** [comment]
CircleCI passing: https://app.circleci.com/pipelines/github/btielen/ssd1306?branch=add_raspberry_example

**Comment by jamwaffles** [comment]
Thanks for the PR! I haven't had much capacity to focus on this crate recently, but this PR gave me a kick to take a look at #133 again as well. IMO, I think the approach in #133 is better as it doesn't require an MSRV bump or Cargo hacks to make work so I'd like to go in that direction if you don't mind. This crate gets quite a lot of downloads so I think it's important to remain compatible even with older Rust versions.

**Comment by btielen** [comment]
No worries, your considerations make sense :)

**Comment by jamwaffles** [comment]
Thanks :). I'll close this PR in favour of #133.

**Pull request closed without merging**
