### PR TITLE
New, more consistent terminal font

### LINKED ISSUE #135: Inconsistent Uppercase Font in Terminal Mode
- Version of `ssd1306` in use (if applicable): `0.4.0`
- MCU/other hardware in use: atmega328p
- Display resolution and interface: [I2C], [128x64]

## Description of the problem/feature request/other

Several uppercase characters in terminal mode are bold, inconsistent with the rest. The characters in question are `DLORW`, which use 2-3 pixel font instead of 1 pixel like the rest of the characters.

## Example code and result:

```rust
let interface = I2CDIBuilder::new().init(i2c);
let mut disp: TerminalMode<_> = Builder::new().connect(interface).into();

disp.init().unwrap();

disp.clear().unwrap();

for c in "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|".chars() {
    disp.print_char(c);
}
```
oled_font

### PR DESCRIPTION
**Pull request by jamwaffles**
Hi! Thank you for helping out with SSD1306 development! Please:

- [x] Check that you've added documentation to any new methods
- [x] Rebase from `master` if you're not already up to date
- [x] Add or modify an example if there are changes to the public API
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [x] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

This font is taken from the ATIx_550_8x8.png font image from the
romfonts repo. I picked it because it looks nice, but that's subjective. It looks like this:

I don't have hardware to test with tat the moment so I might have messed
up the character mappings. I'd appreciate if someone could test on a
physical display and see how this looks.

I'm not including any of the special characters defined in that font. If
we want to add them, I'd suggest we do that in a future PR.

Closes #135

### CODE REVIEW

**Comment by therealprof** [comment]
> This font is taken from the ATIx_550_8x8.png font image from the
> romfonts repo.

Could there be a copyright issue?

It's certainly very retro. ;)

**Comment by jamwaffles** [comment]
Yeah, I did think about copyright but decided to use it anyway :grimacing:. 
Should we continue with the current choice anyway?

The [Uzebox wiki](http://uzebox.org/wiki/Font_Bitmaps#8x8) has some alternative 8x8 fonts but a) "Some may still be under copyright" and b) I can't be bothered to turn the bitmaps into hex :(

**Comment by therealprof** [comment]
Have you checked out sites like: https://jared.geek.nz/2014/jan/custom-fonts-for-microcontrollers ?

**Comment by jamwaffles** [comment]
I haven't, thanks for the link! Any idea what the copyright is like? I'll have a look through those fonts and find something suitable.

**Comment by jamwaffles** [comment]
Honestly, none of them look that good. I'm ok going with the original font for now.

**Comment by jamwaffles** [comment]
I took some time to switch to `zxpix` from <https://jared.geek.nz/2014/jan/custom-fonts-for-microcontrollers>. It's converted from TTF to bitmap, so there were some artifacts in a few of the characters, mostly the lowercase ones. I've fixed those manually. Licensing shouldn't be an issue now.

**Comment by jamwaffles** [comment]
image

Looks like this now.

**Comment by therealprof** [comment]
Nice! 👍

**Pull request merged**
